import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NotistackProvider from "./providers/NotiStackProvider";

const inter = Inter({ subsets: ["latin"] });

const style = {
  backgroundImage: "url('/Img.png')",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={style}>
        <NotistackProvider>{children}</NotistackProvider>
      </body>
    </html>
  );
}
