import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NotistackProvider from "./providers/NotiStackProvider";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reserva de citas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box
          sx={{
            backgroundImage: "url('/Img.png')",
            backgroundRepeat: "round",
            width: "30%",
            height: "30%",
            position: "absolute",
            zIndex: -1,
          }}
        ></Box>
        <Box
          sx={{
            backgroundImage: "url('/Bg.png')",
            backgroundRepeat: "round",
            width: "30%",
            height: "30%",
            position: "absolute",
            zIndex: -1,
            right: 0,
            bottom: 0,
          }}
        ></Box>
        <NotistackProvider>{children}</NotistackProvider>
      </body>
    </html>
  );
}
